name: apapedia_mobile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  jwt_decoder: ^2.0.1
  dio: ^5.3.3
  http: ^0.13.0
  font_awesome_flutter: ^10.1.0
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  bloc: ^7.0.0
  equatable: ^2.0.5
  flutter_bloc: ^7.0.0
  flutter_datetime_picker: ^1.5.1
  top_snackbar_flutter: ^3.1.0
  provider: any
  flutterflow_ui: 0.2.0+1
  auto_size_text: 3.0.0
  # cached_network_image: 3.2.1
  # flutter_animate: 4.1.1+1
  # flutter_cache_manager: 3.3.1
  # from_css_color: 2.0.0
  # go_router: 7.1.1
  # google_fonts: any
  # json_path: 0.6.2
  # page_transition: 2.1.0
  # path_provider: 2.0.14
  # path_provider_android: 2.0.25
  # path_provider_foundation: 2.2.2
  # path_provider_platform_interface: 2.0.6
  # shared_preferences: 2.2.2
  # shared_preferences_android: 2.2.1
  # shared_preferences_foundation: 2.3.4
  # shared_preferences_platform_interface: 2.3.1
  # shared_preferences_web: 2.2.1
  # sqflite: 2.2.6
  # timeago: 3.2.2
  # url_launcher: 6.1.10
  # url_launcher_android: 6.0.27
  # url_launcher_ios: 6.1.4
  # url_launcher_platform_interface: 2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

